"""downloads"""

from alembic import op
import sqlalchemy as sa

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", "revision"),
    )
    op.create_table(
        "downloads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("infohash", sa.String(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("save_path", sa.Text(), nullable=False),
        sa.Column("torrent_file", sa.Text(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("manual_paused", sa.Boolean(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("uploaded", sa.Integer(), nullable=False),
        sa.Column("downloaded", sa.Integer(), nullable=False),
        sa.Column("seed_ratio", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("infohash"),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("download_id", sa.Integer(), nullable=False),
        sa.Column("video_index", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("tracks", sa.JSON(), nullable=False),
        sa.Column("resolution", sa.Integer(), nullable=True),
        sa.Column("probe", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["download_id"],
            ["downloads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("download_id", "video_index"),
    )
    op.create_table(
        "subtask_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subtask_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("preflight", sa.JSON(), nullable=False),
        sa.Column("verification", sa.JSON(), nullable=False),
        sa.Column("override", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["media_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subtask_id"],
            ["subtasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subtask_id", "asset_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subtask_assets")
    op.drop_table("media_assets")
    op.drop_table("downloads")
    op.drop_table("releases")
    # ### end Alembic commands ###
